from random import randint
import time

if __name__ == '__main__':
    n = int(input("n (large prime number): ")) # 479 001 599
    g = int(input("g (prime smaller than n): ")) # 39 916 801

    # n = 170141183460469231731687303715884105727
    # g = 2305843009213693951

    privKeyA = randint(10000, 100000)
    privKeyB = randint(10000, 100000)
    print("A's private key: " + str(privKeyA))
    print("B's private key: " + str(privKeyB))

    factorA = (g ** privKeyA) % n
    factorB = (g ** privKeyB) % n

    keyA = factorB ** privKeyA % n      # = ( g ^ (b*a) ) mod n = (((g ^ b) mod n) ^ a) mod n
    keyB = factorA ** privKeyB % n      # = ( g ^ (a*b) ) mod n

    print("Public key generated by A: " + str(keyA) + "\nPublic key generated by B: " + str(keyB))
